### ISSUE TITLE
Make fails with malformed import path error

### ISSUE THREAD

**Issue by maksadbek** [uber-common/cadence-samples#41]
Trying to compile with Go1.16 but `make` fails with the following error:

```
go build -i -o bin/helloworld cmd/samples/recipes/helloworld/*.go
cmd/samples/common/factory.go:7:2: malformed import path "go.uber.org/cadence/.gen/go/cadence/workflowserviceclient": leading dot in path element
../../gocode/pkg/mod/go.uber.org/cadence@v0.16.0/internal/internal_workflow_testsuite.go:40:2: malformed import path "go.uber.org/cadence/.gen/go/cadence/workflowservicetest": leading dot in path element
cmd/samples/common/sample_helper.go:6:2: malformed import path "go.uber.org/cadence/.gen/go/shared": leading dot in path element
make: *** [helloworld] Error 1
```

**Comment by yycptt** [comment]
Thanks for reporting. Updating to the latest go version should solve this issue. 

I am using 1.16.3 and the build works for me.

**Comment by Ash-win** [comment]
go version ==>>go version go1.20.5 windows/amd64

Still getting the following error.

Access denied - ./CMD/SAMPLES/COMMON
File not found - -NAME
go build -o bin/helloworld ./cmd/samples/recipes/helloworld/*.go
CreateFile cadence-samples\cmd\samples\recipes\helloworld\*.go: The filename, directory name, or volume label syntax is incorrect.
make: *** [Makefile:76: helloworld] Error 1
